CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    alert_kind VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    bucket VARCHAR(32) NOT NULL,
    message VARCHAR(1024) NOT NULL,
    sent_at BIGINT NOT NULL,
    delivery_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    error_message VARCHAR(1024) NULL,
    retry_count INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_notification_site_sent ON notification(site_id, sent_at);
