CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    url VARCHAR(512) NOT NULL,
    category_id BIGINT NOT NULL,
    availability_status VARCHAR(16) NULL,
    last_checked_at BIGINT NULL,
    certificate_expires_at BIGINT NULL,
    domain_expires_at BIGINT NULL,
    certificate_issuer VARCHAR(256) NULL,
    paused BOOLEAN NOT NULL DEFAULT FALSE,
    consecutive_failures_before_alert INT NULL,
    consecutive_availability_failures INT NOT NULL DEFAULT 0,
    cert_forgive VARCHAR(255) NULL,
    maintenance VARCHAR(256) NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_site_name UNIQUE (name),
    CONSTRAINT uk_site_url UNIQUE (url)
);

CREATE INDEX idx_site_category ON site(category_id);
