CREATE TABLE site_path_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    path VARCHAR(512) NOT NULL,
    expected_http_status INT NOT NULL,
    last_checked_at BIGINT NULL,
    last_http_status INT NULL,
    last_error_message VARCHAR(512) NULL,
    consecutive_failures INT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX idx_site_path_rule_site ON site_path_rule(site_id);
