CREATE TABLE site_check_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    checked_at BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    http_status INT NULL,
    response_ms INT NULL,
    error_message VARCHAR(512) NULL
);

CREATE INDEX idx_site_checked ON site_check_history(site_id, checked_at);
CREATE INDEX idx_checked_status ON site_check_history(checked_at, status);
