-- H2 测试库：子路由探测历史。
CREATE TABLE site_path_check_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    path VARCHAR(512) NOT NULL,
    checked_at BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    http_status INT NULL,
    text_matched BOOLEAN NULL,
    error_message VARCHAR(512) NULL
);
CREATE INDEX idx_rule_checked ON site_path_check_history(rule_id, checked_at);
CREATE INDEX idx_site_checked ON site_path_check_history(site_id, checked_at);
CREATE INDEX idx_path_hist_checked ON site_path_check_history(checked_at);
